"use client";
import { useState } from "react";
import { Check, Copy, LoaderCircle, Send } from "lucide-react";
import { postSignedMessage, RateLimitError } from "@/lib/technocore";
import type { SignedActivity } from "@/lib/types";
import { copyTextToClipboard } from "@/lib/utils";
import { NormalizedPreview } from "@/components/posting/NormalizedPreview";
import { TemplateSelect } from "@/components/posting/TemplateSelect";
import { TEMPLATES, type TemplateId } from "@/lib/technocore/templates";
export function MessageComposer({ did, privateKey, initialRoom = "lobby", initialText = "", onDraft, onPosted }: { did: string | null; privateKey: Uint8Array | null; initialRoom?: string; initialText?: string; onDraft?: (draft: { room?: string; text?: string }) => void; onPosted: (activity: SignedActivity) => void }) { const [room, setRoom] = useState(initialRoom); const [text, setText] = useState(initialText); const [template, setTemplate] = useState<TemplateId | "custom">("custom"); const [error, setError] = useState(""); const [posting, setPosting] = useState(false); const [cooldown, setCooldown] = useState(0); const [result, setResult] = useState<{ sequence: number; nonce: string; text: string } | null>(null); const [copied, setCopied] = useState(false); function selectTemplate(value: TemplateId | "custom") { setTemplate(value); if (value !== "custom") { const selected = TEMPLATES[value]; setRoom(selected.room); setText(selected.text); onDraft?.({ room: selected.room, text: selected.text }); } }
	async function submit() { if (!did || !privateKey) { setError("Unlock DID first."); return; } setPosting(true); setError(""); try { const posted = await postSignedMessage({ room, text, did, privateKeyBytes: privateKey }); setResult({ sequence: posted.seq ?? 0, nonce: posted.nonce, text: posted.text }); onPosted({ id: `${did}:${room}:${posted.nonce}`, did, room, sequence: posted.seq ?? 0, nonce: posted.nonce, text: posted.text, timestamp: posted.timestamp ?? new Date().toISOString(), type: "custom" }); } catch (caught) { if (caught instanceof RateLimitError) { setCooldown(caught.waitSeconds); window.setTimeout(() => setCooldown(0), caught.waitSeconds * 1000); } setError(caught instanceof Error ? caught.message : "Could not post message."); } finally { setPosting(false); } }
	async function copyResult() { if (!result) return; const success = await copyTextToClipboard(`Room: ${room}\nSequence: ${result.sequence}\nNonce: ${result.nonce}\nText: ${result.text}`); if (success) { setCopied(true); window.setTimeout(() => setCopied(false), 1500); } }
	return <section className="rounded-2xl border border-zinc-800 bg-zinc-900/30 p-5 sm:p-6"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm text-zinc-300">Room<select value={room} onChange={(event) => { setRoom(event.target.value); onDraft?.({ room: event.target.value }); }} className="mt-2 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2.5 text-sm outline-none focus:border-emerald-400"><option>lobby</option><option>technocore</option></select></label><TemplateSelect value={template} onChange={selectTemplate} /></div><label className="mt-4 block text-sm text-zinc-300">Message<textarea value={text} onChange={(event) => { setText(event.target.value); onDraft?.({ text: event.target.value }); }} maxLength={4096} rows={5} className="mt-2 w-full resize-y rounded-lg border border-zinc-700 bg-zinc-950 p-3 text-sm outline-none focus:border-emerald-400" /><span className="mt-1 block text-right text-xs text-zinc-600">{text.length}/4096</span></label><div className="mt-4"><NormalizedPreview room={room} text={text} /></div>{error && <p className="mt-4 rounded-lg border border-red-400/20 bg-red-400/5 p-3 text-sm text-red-300">{error}</p>}<button disabled={posting || cooldown > 0 || !text.trim()} onClick={submit} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-emerald-400 px-4 py-2.5 text-sm font-semibold text-zinc-950 disabled:cursor-not-allowed disabled:opacity-40">{posting ? <LoaderCircle className="animate-spin" size={16} /> : <Send size={16} />}{posting ? "Posting..." : cooldown ? `Try again in ${cooldown}s` : "Post Signed Message"}</button>{result && <div className="mt-4 rounded-lg border border-emerald-400/20 bg-emerald-400/5 p-4 text-sm"><p className="font-medium text-emerald-300">Message posted</p><p className="mt-2 text-xs text-zinc-400">Sequence: {result.sequence} · Nonce: <span className="font-mono">{result.nonce}</span></p><p className="mt-2 break-words text-zinc-300">{result.text}</p><button onClick={() => void copyResult()} className="mt-3 inline-flex items-center gap-2 text-xs text-zinc-400 hover:text-zinc-200">{copied ? <Check size={14} /> : <Copy size={14} />}{copied ? "Copied" : "Copy result"}</button></div>}</section>; }
