"use client";
import { useEffect, useState } from "react";
import { LoaderCircle, RefreshCw } from "lucide-react";
import { ActivityFilters, type ActivityFilterState } from "@/components/activity/ActivityFilters";
import { ActivityTable } from "@/components/activity/ActivityTable";
import { MessageComposer } from "@/components/posting/MessageComposer";
import { getActivityByDid, getRoomMessages, type RoomMessage } from "@/lib/technocore";
import type { SignedActivity } from "@/lib/types";
import { copyTextToClipboard } from "@/lib/utils";
import { useAppStore } from "@/store/useAppStore";

function toActivity(message: RoomMessage & { room?: string }, did: string): SignedActivity { const sequence = message.seq ?? message.sequence ?? 0; return { id: `${did}:${message.room}:${sequence}`, did, room: message.room ?? "unknown", sequence, nonce: message.nonce ?? "remote", text: message.text ?? "", timestamp: message.timestamp ?? new Date().toISOString(), type: "custom" }; }
export default function ActivityPage() {
  const did = useAppStore((state) => state.activeDid); const privateKey = useAppStore((state) => state.unlockedPrivateKey); const activities = useAppStore((state) => state.activities); const addActivity = useAppStore((state) => state.addActivity); const replaceActivities = useAppStore((state) => state.replaceActivities); const draft = useAppStore((state) => state.messageDraft); const updateDraft = useAppStore((state) => state.updateDraft); const [filters, setFilters] = useState<ActivityFilterState>({ room: "all", type: "all", search: "" }); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function refresh() { if (!did) return; setLoading(true); setError(""); try { const rooms = filters.room === "all" ? ["lobby", "technocore"] : filters.room === "custom" ? [] : [filters.room]; const remote = (await Promise.all(rooms.map((room) => getActivityByDid(did, [room])))).flat(); const incoming = remote.map((item) => toActivity(item, did)); const existing = useAppStore.getState().activities; const byKey = new Map(existing.map((item) => [`${item.did}:${item.room}:${item.sequence}`, item])); incoming.forEach((item) => { const key = `${item.did}:${item.room}:${item.sequence}`; if (!byKey.has(key)) byKey.set(key, item); }); replaceActivities([...byKey.values()]); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not refresh activity."); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); }, [did]);
  const own = did ? activities.filter((item) => item.did === did) : []; const visible = own.filter((item) => (filters.room === "all" || (filters.room === "custom" ? !["lobby", "technocore"].includes(item.room) : item.room === filters.room)) && (filters.type === "all" || item.type === filters.type) && (!filters.search || `${item.text} ${item.sequence} ${item.room}`.toLowerCase().includes(filters.search.toLowerCase()))).sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
  return <div className="space-y-8"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-400">Signed history</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">Activity ledger</h1><p className="mt-3 max-w-xl text-sm leading-6 text-zinc-500">Post messages, filter your records, and inspect signed payload details.</p></div><MessageComposer did={did} privateKey={privateKey} initialRoom={draft.room} initialText={draft.text} onDraft={(value) => updateDraft(value)} onPosted={(item) => addActivity(item)} /><section className="rounded-2xl border border-zinc-800 bg-zinc-900/30 p-5 sm:p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="font-semibold text-zinc-100">Your activity</h2><p className="mt-1 text-xs text-zinc-600">{visible.length} matching record{visible.length === 1 ? "" : "s"}</p></div><button onClick={() => void refresh()} disabled={loading || !did} className="inline-flex items-center gap-2 text-sm text-emerald-400 disabled:opacity-40"><RefreshCw size={15} className={loading ? "animate-spin" : ""} />Refresh</button></div><div className="mt-5"><ActivityFilters value={filters} onChange={setFilters} /></div>{error && <p className="mt-4 text-sm text-red-300">{error}</p>}{loading ? <div className="flex items-center gap-2 py-10 text-sm text-zinc-500"><LoaderCircle className="animate-spin" size={16} />Refreshing records...</div> : visible.length ? <div className="mt-5"><ActivityTable items={visible} onCopy={(item) => void copyTextToClipboard(`Signed Technocore record: room ${item.room}, sequence ${item.sequence}`)} onIntro={(item) => addActivity({ ...item, type: "intro" })} /></div> : <div className="py-10 text-center text-sm text-zinc-500">No activity yet. Post a signed message above to create your first record.</div>}</section></div>;
}
