"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, Fingerprint, X } from "lucide-react";
import { Checklist } from "@/components/dashboard/Checklist";
import { IntroModal } from "@/components/dashboard/IntroModal";
import { NextStepBanner, type NextStep } from "@/components/dashboard/NextStepBanner";
import { QuickActions } from "@/components/dashboard/QuickActions";
import { RecentActivity } from "@/components/dashboard/RecentActivity";
import { StatsRow } from "@/components/dashboard/StatsRow";
import { StatusStrip } from "@/components/dashboard/StatusStrip";
import { UnlockCard } from "@/components/dashboard/UnlockCard";
import { getActivityByDid } from "@/lib/technocore";
import type { SignedActivity } from "@/lib/types";
import { copyTextToClipboard } from "@/lib/utils";
import { useAppStore } from "@/store/useAppStore";

function activityFromRemote(message: { did?: string; from?: string; room?: string; text?: string; nonce?: string; seq?: number; sequence?: number; timestamp?: string; ts?: string }): SignedActivity { const did = message.from ?? message.did ?? ""; const sequence = message.seq ?? message.sequence; return { id: `${did}:${message.room}:${message.nonce ?? sequence ?? "remote"}`, did, room: message.room ?? "unknown", sequence, nonce: message.nonce ?? "remote", text: message.text ?? "", timestamp: (typeof message.ts === "string" ? message.ts : undefined) ?? message.timestamp ?? new Date().toISOString(), type: "custom" }; }

export default function Home() {
  const identities = useAppStore((state) => state.identities); const activeDid = useAppStore((state) => state.activeDid); const unlockedPrivateKey = useAppStore((state) => state.unlockedPrivateKey); const activities = useAppStore((state) => state.activities); const contributions = useAppStore((state) => state.contributions); const addActivity = useAppStore((state) => state.addActivity); const replaceActivities = useAppStore((state) => state.replaceActivities); const unlockIdentity = useAppStore((state) => state.unlockIdentity);
  const identity = identities.find((item) => item.did === activeDid); const unlocked = !!unlockedPrivateKey && !!identity; const myActivities = activeDid ? activities.filter((item) => item.did === activeDid).sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()) : []; const myContributions = activeDid ? contributions.filter((item) => item.did === activeDid) : []; const hasLobbyIntro = myActivities.some((item) => item.type === "intro" && item.room === "lobby"); const hasContributionRecord = myContributions.length > 0 || myActivities.some((item) => item.type === "contribution");
  const [introOpen, setIntroOpen] = useState(false); const [unlockingDid, setUnlockingDid] = useState<string | null>(null); const [unlockPassphrase, setUnlockPassphrase] = useState(""); const [unlockError, setUnlockError] = useState(""); const [refreshError, setRefreshError] = useState(""); const [copied, setCopied] = useState(false);
  async function refresh() { if (!activeDid || !unlocked) return; setRefreshError(""); try { const remote = await getActivityByDid(activeDid); const localForDid = activities.filter((item) => item.did === activeDid); const mapped = remote.map((message) => { const next = activityFromRemote(message); const previous = localForDid.find((item) => item.id === next.id || (item.room === next.room && item.text === next.text)); return previous ? { ...next, type: previous.type } : next; }); const mappedIds = new Set(mapped.map((item) => item.id)); const mappedKeys = new Set(mapped.map((item) => `${item.room}::${item.text}`)); replaceActivities([...mapped, ...activities.filter((item) => item.did !== activeDid || (!mappedIds.has(item.id) && !mappedKeys.has(`${item.room}::${item.text}`)))]); } catch (error) { setRefreshError(error instanceof Error ? error.message : "Could not refresh activity."); } }
  async function submitUnlock() { if (!unlockingDid) return; setUnlockError(""); if (!unlockPassphrase.trim()) { setUnlockError("Enter the DID passphrase."); return; } try { await unlockIdentity(unlockingDid, unlockPassphrase); setUnlockingDid(null); setUnlockPassphrase(""); setUnlockError(""); } catch (error) { setUnlockError(error instanceof Error ? error.message : "Could not unlock DID."); } }
  useEffect(() => { if (unlocked) void refresh(); }, [activeDid, unlocked]);
  async function copy(value: string) { const success = await copyTextToClipboard(value); if (success) { setCopied(true); window.setTimeout(() => setCopied(false), 1600); } }
  function copyProof() { const intro = myActivities.find((item) => item.type === "intro" && item.room === "lobby"); if (identity) void copy(`Technocore proof\nDID: ${identity.did}\nFingerprint: ${identity.fingerprint}\nLobby intro: room lobby, sequence ${intro?.sequence ?? "not recorded"}\nLast activity: ${myActivities[0]?.timestamp ?? "none"}`); }
  const step: NextStep = !identity ? { title: "Create or import a DID", description: "A persistent identity is the starting point for verifiable Technocore activity.", label: "Set up DID", href: "/dids" } : !unlocked ? { title: "Unlock your DID to continue", description: "Your encrypted identity is saved locally. Unlock it to sign and read your activity.", label: "Unlock DID", onClick: () => { setUnlockingDid(identity.did); setUnlockPassphrase(""); setUnlockError(""); } } : !hasLobbyIntro ? { title: "Post your first signed introduction", description: "Technocore needs a signed lobby message from this DID before later records mean much.", label: "Post Introduction", onClick: () => setIntroOpen(true) } : !hasContributionRecord ? { title: "Record a useful contribution", description: "Connect your signed identity to public work when you are ready.", label: "Record Contribution", href: "/contributions" } : { title: "Generate a proof pack", description: "Your identity and contribution trail are ready to be packaged later.", label: "View Contributions", href: "/contributions" };
  if (!identity) return <div className="space-y-8"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-400">Control center</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">Your Technocore workspace</h1></div><section className="flex flex-col items-center rounded-2xl border border-dashed border-zinc-800 bg-zinc-950/40 px-6 py-16 text-center"><Fingerprint className="text-emerald-400" size={32} /><h2 className="mt-5 text-xl font-semibold text-zinc-100">Create or import a DID</h2><p className="mt-2 max-w-md text-sm leading-6 text-zinc-500">Set up an encrypted identity to start signing verifiable messages.</p><Link href="/dids" className="mt-6 inline-flex items-center gap-2 rounded-lg bg-emerald-400 px-4 py-2.5 text-sm font-semibold text-zinc-950">Set up a DID <ArrowRight size={16} /></Link></section></div>;
  return <div className="space-y-6"><StatusStrip did={identity.did} fingerprint={identity.fingerprint} unlocked={unlocked} onCopy={() => void copy(`DID: ${identity.did}\nFingerprint: ${identity.fingerprint}`)} onUnlock={() => { setUnlockingDid(identity.did); setUnlockPassphrase(""); setUnlockError(""); }} /><NextStepBanner step={step} locked={!unlocked} />{unlocked ? <><StatsRow did={identity.did} fingerprint={identity.fingerprint} posts={myActivities.length} contributions={myContributions.length} lastActivity={myActivities[0] ? new Date(myActivities[0].timestamp).toLocaleString() : "No activity yet"} status={hasContributionRecord ? "Ready" : hasLobbyIntro ? "Intro complete" : "Intro needed"} /><QuickActions locked={!unlocked} hasActivity={myActivities.length > 0} onIntro={() => setIntroOpen(true)} onRefresh={() => void refresh()} onCopy={copyProof} /><div className="grid gap-6 lg:grid-cols-[1.4fr_0.8fr]"><RecentActivity activities={myActivities} error={refreshError} onRetry={() => void refresh()} /><Checklist items={[{ label: "DID created", complete: true }, { label: "DID unlocked", complete: unlocked }, { label: "Signed lobby introduction", complete: hasLobbyIntro }, { label: "Contribution recorded", complete: hasContributionRecord }]} /></div></> : <UnlockCard onUnlock={() => { setUnlockingDid(identity.did); setUnlockPassphrase(""); setUnlockError(""); }} />} {copied && <span className="fixed bottom-5 right-5 rounded-lg border border-emerald-400/30 bg-zinc-900 px-3 py-2 text-xs text-emerald-300">Copied</span>} {unlockingDid && <div className="fixed inset-0 z-30 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-md rounded-2xl border border-zinc-700 bg-zinc-900 p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="text-xl font-semibold text-zinc-100">Unlock DID</h2><p className="mt-2 break-all font-mono text-xs text-zinc-400">{unlockingDid}</p></div><button aria-label="Close" title="Close" onClick={() => { setUnlockingDid(null); setUnlockPassphrase(""); setUnlockError(""); }} className="text-zinc-500 hover:text-zinc-200"><X size={18} /></button></div><label className="mt-6 block text-sm text-zinc-300">Passphrase <input type="password" value={unlockPassphrase} onChange={(event) => setUnlockPassphrase(event.target.value)} className="mt-2 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2.5 text-sm outline-none focus:border-emerald-400" placeholder="Enter your DID passphrase" /></label>{unlockError && <p className="mt-4 text-sm text-red-300">{unlockError}</p>}<button onClick={() => void submitUnlock()} className="mt-6 w-full rounded-lg bg-emerald-400 px-4 py-3 text-sm font-semibold text-zinc-950 hover:bg-emerald-300">Unlock identity</button></div></div>} {introOpen && unlockedPrivateKey && <IntroModal did={identity.did} privateKey={unlockedPrivateKey} onClose={() => setIntroOpen(false)} onPosted={(activity) => { addActivity(activity); void refresh(); }} />}</div>;
}
