"use client";
import Link from "next/link";
import { useState } from "react";
import { Copy, Fingerprint, LockKeyhole } from "lucide-react";
import { MissingPieces } from "@/components/proof/MissingPieces";
import { ProofExport } from "@/components/proof/ProofExport";
import { ProofPreview } from "@/components/proof/ProofPreview";
import { ProofStatus } from "@/components/proof/ProofStatus";
import { buildProofPack } from "@/lib/proof";
import type { ProofPack } from "@/lib/proof";
import { useAppStore } from "@/store/useAppStore";

export default function ProofPage() {
  const identities = useAppStore((state) => state.identities); const activeDid = useAppStore((state) => state.activeDid); const activities = useAppStore((state) => state.activities); const contributions = useAppStore((state) => state.contributions); const identity = identities.find((item) => item.did === activeDid); const pack = activeDid ? buildProofPack(activeDid, identities, activities, contributions) : null; const [copied, setCopied] = useState(false);
  function markCopied() { setCopied(true); window.setTimeout(() => setCopied(false), 1500); }
  if (!identity || !pack) return <div className="space-y-8"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-400">Evidence trail</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">Proof pack</h1></div><section className="flex flex-col items-center rounded-2xl border border-dashed border-zinc-800 p-12 text-center"><Fingerprint className="text-zinc-600" size={30} /><p className="mt-4 text-sm text-zinc-300">Create or select a DID to build a proof pack.</p><Link href="/dids" className="mt-5 rounded-lg bg-emerald-400 px-4 py-2.5 text-sm font-semibold text-zinc-950">Manage DIDs</Link></section></div>;
  const checks = [{ label: "DID exists", complete: true }, { label: "Lobby intro found", complete: !!pack.lobbyIntro }, { label: "At least one contribution found", complete: !!pack.primaryContribution }, { label: "Primary contribution selected", complete: !!pack.primaryContribution }, { label: "Required sequence numbers present", complete: !!pack.lobbyIntro?.sequence && !!pack.primaryContribution?.sequence }];
  return <div className="space-y-6"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-400">Evidence trail</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">Proof pack</h1><p className="mt-3 max-w-xl text-sm leading-6 text-zinc-500">A portable record of what this DID has signed on Technocore.</p></div><section className="rounded-xl border border-zinc-800 bg-zinc-900/30 p-5"><p className="text-xs uppercase tracking-wider text-zinc-500">Identity</p><p className="mt-3 break-all font-mono text-sm text-zinc-200">{pack.did}</p><p className="mt-2 font-mono text-xs text-zinc-500">Fingerprint: {pack.fingerprint} · {pack.label}</p><p className="mt-3 flex items-center gap-2 text-xs text-zinc-600"><LockKeyhole size={13} />Private keys and passphrases are never included.</p></section><ProofStatus checks={checks} /><MissingPieces hasIntro={!!pack.lobbyIntro} hasContribution={!!pack.primaryContribution} hasSequence={!!pack.lobbyIntro?.sequence && !!pack.primaryContribution?.sequence} /><ProofPreview pack={pack} />{pack.primaryContribution && <section className="rounded-xl border border-zinc-800 bg-zinc-900/30 p-5"><p className="text-xs uppercase tracking-wider text-zinc-500">Primary contribution</p><p className="mt-3 break-all text-sm text-zinc-200">{pack.primaryContribution.publicUrl}</p><p className="mt-2 text-sm text-zinc-500">Room {pack.primaryContribution.room} · Sequence {pack.primaryContribution.sequence} · {pack.primaryContribution.createdAt}</p></section>}<ProofExport pack={pack} onCopied={markCopied} />{copied && <span className="fixed bottom-5 right-5 inline-flex items-center gap-2 rounded-lg border border-emerald-400/30 bg-zinc-900 px-3 py-2 text-xs text-emerald-300"><Copy size={13} />Copied</span>}</div>;
}
